<a href="https://colab.research.google.com/github/datbrowndude/fcrossed/blob/main/fcrossed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#download data from kaggle or python library to scrape the images

In [10]:
!pip install ipython-autotime
%load_ext autotime

time: 159 µs


In [1]:
!pip install bing-image-downloader

In [2]:
!mkdir imagess

In [8]:
from bing_image_downloader import downloader
downloader.download("light blue", limit=30, output_dir='imagess',
                    adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from http://wallpapercave.com/wp/6ERktAi.png
[%] File Downloaded !

[%] Downloading Image #2 from https://i.ytimg.com/vi/eTjV-z1WSd4/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://wallpapercave.com/wp/wp2590325.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://images.freecreatives.com/wp-content/uploads/2016/02/Light-Sky-Blue-Solid-Color-Background.jpg
[%] File Downloaded !

[%] Downloading Image #5 from http://wallpapercave.com/wp/4Vsv2Bs.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://wallpapercave.com/wp/fto5lYX.jpg
[%] File Downloaded !

[%] Downloading Image #7 from http://wallpapercave.com/wp/jgZcrie.jpg
[%] File Downloaded !

[%] Downloading Image #8 from http://wallpapercave.com/wp/nf2pXZp.jpg
[%] File Downloaded !

[%] Downloading Image #9 from http://wallpapercave.com/wp/UGOcPA9.jpg
[%] File Downloaded !

[%] Downloading Image #10

In [9]:
downloader.download("dark blue", limit=30, output_dir='imagess',
                    adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://dyrdkqpaj50j2.cloudfront.net/media/catalog/product/cache/24/thumbnail/9df78eab33525d08d6e5fb8d27136e95/d/a/dark_blue-1299-sud-c.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://www.drodd.com/images16/dark-blue11.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://www.rrts.com/wp-content/uploads/2018/09/Blue-Background.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://www.themely.com/wp-content/uploads/edd/2015/11/dark-blue-bg.png
[%] File Downloaded !

[%] Downloading Image #5 from https://www.drodd.com/images16/dark-blue3.png
[%] File Downloaded !

[%] Downloading Image #6 from https://www.targetsolutions.com/wp-content/uploads/2016/01/dark-blue-square.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://www.microsoft.com/en-us/research/wp-content/uploads/2017/06/Dark-Blue-Header.jpg
[%] File Downloaded !

[%] Downloading Image #8 fro

In [22]:
#preprocess data
#1. resize    2. flatten
import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize
target=[]
imagess=[]
flat_data=[]

DATADIR='/content/imagess'
CATEGORIES=['light blue','dark blue']
for category in CATEGORIES:
 class_num =CATEGORIES.index(category)  # indexing categories lightblue and darkblue
 path=os.path.join(DATADIR,category)  #path created to use images
 for img in os.listdir(path):
   img_array=imread(os.path.join(path,img))
   #print(img_array)
   #plt.imshow(img_array)
   img_resized=resize(img_array,(150,150,3)) #normalises intensity values from 0 to 1
   flat_data.append(img_resized.flatten())
   imagess.append(img_resized)
   target.append(class_num)

flat_data=np.array(flat_data)
target=np.array(target)
imagess=np.array(imagess)
  

time: 1min 18s


In [24]:
flat_data[0]

array([0.64313725, 0.99607843, 0.98823529, ..., 0.62352941, 0.99215686,
       0.98039216])

time: 4.47 ms


In [25]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

time: 3.55 ms


In [26]:
#split data to train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(flat_data,target,test_size=0.3,random_state=109)

time: 18.1 ms


In [27]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid=[
            {'C':[1,10,100,1000], 'kernel':['linear']},
            {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']}
]
svc = svm.SVC(probability=True)
clf=GridSearchCV(svc,param_grid)
clf.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

time: 22.1 s


In [28]:
y_pred=clf.predict(x_test)
y_pred

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0])

time: 22.7 ms


In [29]:
y_test

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0])

time: 3.52 ms


In [30]:
from sklearn.metrics import accuracy_score,confusion_matrix

time: 1.19 ms


In [31]:
accuracy_score(y_pred,y_test)

0.9444444444444444

time: 3.17 ms


In [32]:
confusion_matrix(y_pred,y_test)

array([[11,  1],
       [ 0,  6]])

time: 11.5 ms


In [33]:
#Saving model in pickle
import pickle
pickle.dump(clf,open('img_model.p','wb'))

time: 9.85 ms


In [34]:
model=pickle.load(open('img_model.p','rb'))

time: 16.6 ms


In [ ]:
#testing new image
flat_data=[]
url=input('enter url')
img=imread(url)
img_resized=resize(img_array,(150,150,3))  
flat_data.append(img_resized.flatten())
flat_data=np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out=model.predict(flat_data)
y_out=CATEGORIES[y_out[0]]
print(f' PREDICTED OUTPUT: {y_out}')